CrystalProjectTracker/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrystalProjectTracker.Models
{
    public class Project
    {
        [Display(Name = "Project Id")]
        public virtual int project_id { get; set; }

        private string ProjectName { get; set; }

        private int ProjectStatus { get; set; }

        private string ProjectDescription { get; set; }

        [Display(Name = "Created")]
        public virtual DateTime created_at { get; set; }

        public virtual ICollection<Module> modules { get; set; }

        [Display(Name = "Project Name")]

        public virtual string project_name
        {
            get => ProjectName;
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                {
                    throw new Exception("Project Name Should not be empty");
                }
                ProjectName = value;
            }
        }

        [Display(Name = "Project Status")]
        public virtual int project_status
        {
            get => ProjectStatus;
            set
            {
                if(value < 0 || value > 1)
                {
                    throw new Exception("Project Status cannot be except 0 and 1");
                }
                ProjectStatus = value;
            }
        }

        [Display(Name = "Project Description")]
        public virtual string project_description
    {
            get => ProjectDescription;
            set
            {
                if(string.IsNullOrWhiteSpace(value))
                {
                    throw new Exception("Project description cannot be empty");
                }
                ProjectDescription = value;
            }
        }
    }
}

CrystalProjectTracker/Controllers/ProjectController.cs
using ClientNotifications;
using CrystalProjectTracker.Repository.ProjectRepository;
using CrystalProjectTracker.Services.DTO;
using CrystalProjectTracker.Services.ProjectService;
using CrystalProjectTracker.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using static ClientNotifications.Helpers.NotificationHelper;


namespace CrystalProjectTracker.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IClientNotification _clientNotification;
        private readonly IProjectService _projectService;
        private readonly IProjectRepository _projectRepository;

        public ProjectController(IProjectRepository projectRepository,IProjectService projectService,IClientNotification clientNotification)
        {
            _clientNotification = clientNotification;
            _projectRepository = projectRepository;
            _projectService = projectService;
        }

        public ActionResult Index()
        {
            var project_list = _projectRepository.getAll();
            var model = new ProjectListViewModel()
            {
                projects = project_list,
                projects_count = project_list.Count
            };
            return View(model);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(ProjectDTO project_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _projectService.Create(project_dto);
                    _clientNotification.AddToastNotification("Project Successfully Created.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var project = _projectRepository.getById(id);
                if (project == null)
                {
                    throw new Exception("Cannot retrive data of that project.");
                }
                return View(project);
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(ProjectDTO project_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _projectService.Update(project_dto);
                    _clientNotification.AddToastNotification("Project Successfully Updated.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Project/Delete
        [HttpPost]
        public ActionResult Delete(int project_id)
        {
            try
            {
                _projectService.Delete(project_id);
                _clientNotification.AddToastNotification("Project Successfully Deleted.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CrystalProjectTracker/Views/Project/Create.cshtml
@model CrystalProjectTracker.Models.Project

@{
    ViewData["Title"] = "Create Project";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-8">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-flask"></i>
                        @ViewData["Title"]
                    </h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <form asp-action="Create">
                                <input type="hidden" asp-for="created_at" value="@DateTime.Now" />
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label asp-for="project_name" class="control-label"></label>
                                        <input asp-for="project_name" class="form-control" required />
                                        <span asp-validation-for="project_name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label asp-for="project_status" class="control-label"></label>
                                        <div class="col-lg-12">
                                            <div class="i-checks" style="margin-top:10px;">
                                                <span><input type="radio" name="project_status" value="1" checked> Activate</span>
                                                <span><input type="radio" name="project_status" value="0"> Deactivate</span>
                                            </div>
                                            <span asp-validation-for="project_status" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <label asp-for="project_description" class="control-label"></label>
                                        <textarea asp-for="project_description" class="form-control" rows="3" id="projectDescriptionTextarea" required></textarea>
                                        <span asp-validation-for="project_description" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <input type="submit" class="btn btn-primary btn-sm" value="Create Project" />
                                        <a asp-action="Index" class="btn btn-default btn-sm pull-right">
                                            <i class="fa fa-close fa-md text-inverse"></i> Cancel
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>New Project</h2>
                            A project is where you house your files, plan your work, and publish your documentation, among other things.
                            All features are enabled for blank projects, from templates, or when importing, but you can disable them afterward in the project settings.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles
    {
    <link rel="stylesheet" href="~/lib/iCheck/skins/all.css" />
}
@section Scripts
    {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/lib/iCheck/icheck.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });

        CKEDITOR.replace('projectDescriptionTextarea');
    </script>
}

CrystalProjectTracker/Views/Project/Edit.cshtml
@model CrystalProjectTracker.Models.Project

@{
    ViewData["Title"] = "Edit Project";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-8">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-flask"></i>
                        @ViewData["Title"]
                    </h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <form asp-action="Edit" asp-controller="Project" method="POST" >
                                <input type="hidden" asp-for="project_id" />
                                <input type="hidden" asp-for="created_at" value="@DateTime.Now" />
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label asp-for="project_name" class="control-label"></label>
                                        <input asp-for="project_name" class="form-control" />
                                        <span asp-validation-for="project_name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label asp-for="project_status" class="control-label"></label>
                                        <div class="col-lg-12">
                                            <div class="i-checks" style="margin-top:10px;">
                                                @{
                                                    if (Model.project_status > 0)
                                                    {
                                                        <span><input type="radio" name="project_status" value="1" checked> Activate</span>
                                                        <span><input type="radio" name="project_status" value="0"> Deactivate</span>
                                                    }
                                                    else
                                                    {
                                                        <span><input type="radio" name="project_status" value="1" > Activate</span>
                                                        <span><input type="radio" name="project_status" value="0" checked> Deactivate</span>
                                                    }
                                                }
                                            </div>
                                            <span asp-validation-for="project_status" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <label asp-for="project_description" class="control-label"></label>
                                        <textarea asp-for="project_description" class="form-control" rows="3" id="projectDescriptionTextarea"></textarea>
                                        <span asp-validation-for="project_description" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <input type="submit" name="submit" class="btn btn-primary btn-sm" value="Edit Project" />
                                        <a asp-action="Index" class="btn btn-default btn-sm pull-right">
                                            <i class="fa fa-close fa-md text-inverse"></i> Cancel
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Project Details</h2>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>Project Name : </dt>
                                <dd>@Model.project_name</dd>
                                <dt>Status : </dt>
                                <dd>
                                    @{
                                        if (Model.project_status > 0)
                                        {
                                            <span class="label label-primary label-md">Active</span>
                                        }
                                        else
                                        {
                                            <span class="label label-default label-md">Unactive</span>
                                        }
                                    }
                                </dd>
                                <dt>Progress : </dt>
                                <dd>
                                    <small>Completion with: 76%</small>
                                    <div class="progress progress-mini">
                                        <div style="width: 76%;" class="progress-bar"></div>
                                    </div>
                                </dd>
                                <dt>Project Description : </dt>
                            </dl>
                            <dl>
                                <dd>@Html.Raw(Model.project_description)</dd>
                            </dl>
                        </div>
                        <div class="col-md-12">
                            <hr />
                            <form asp-action="Delete" asp-controller="Project">
                                <input type="hidden" asp-for="project_id" />
                                <button type="submit" class="btn btn-danger btn-sm btn-block" onclick="return confirm('Are you sure want to delete this project ?');">
                                    <i class="fa fa-trash fa-md text-inverse"></i> Delete Project
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles
    {
    <link rel="stylesheet" href="~/lib/iCheck/skins/all.css" />
}
@section Scripts
    {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/lib/iCheck/icheck.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });

        CKEDITOR.replace('projectDescriptionTextarea');
    </script>
}

CrystalProjectTracker/Views/Project/Index.cshtml
@model CrystalProjectTracker.ViewModel.ProjectListViewModel

@{
    ViewData["Title"] = "Project";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-flask"></i>
                        @ViewData["Title"]
                        @if (Model.projects.Count() > 0)
                        {
                            <span class="badge badge-success">@Model.projects.Count()</span>
                        }
                    </h5>
                    <div class="ibox-tools" style="margin-top:-30px;">
                        <a asp-action="Create" class="btn btn-primary btn-sm">
                            <i class="fa fa-plus fa-md text-inverse"></i> Add Project
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered dataTables-project tooltip-demo">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Project Name</th>
                                        <th>Status</th>
                                        <th>Progress</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.projects)
                                    {
                                    <tr>
                                        <td><i class="fa fa-slack"></i> @item.project_id</td>
                                        <td>
                                            <strong>@item.project_name</strong>
                                        </td>
                                        <td>
                                            @{
                                                if (item.project_status > 0)
                                                {
                                                    <span class="label label-success label-md">Active</span>
                                                }
                                                else
                                                {
                                                    <span class="label label-default label-md">Unactive</span>
                                                }
                                            }
                                        </td>
                                        <td class="project-completion">
                                            <small>Completion with: 48%</small>
                                            <div class="progress progress-mini">
                                                <div style="width: 48%;" class="progress-bar"></div>
                                            </div>
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.project_id" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" data-original-title="Edit Project Details"><i class='fa fa-pencil'></i> Edit</a>
                                            <a href="Module?project_id=@item.project_id" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" data-original-title="Manage Modules"><i class='fa fa-cubes'></i> Manage Modules</a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/js/dataTables/datatables.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/js/dataTables/datatables.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development">
        <script src="~/js/dataTables/datatables.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/dataTables/datatables.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-project').DataTable({
                pageLength: 10,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'Project Detail' },
                    { extend: 'pdf', title: 'Project Detail' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });
        });
    </script>

}