CrystalProjectTracker/Controllers/FeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Base.SessionFactory;
using ClientNotifications;
using CrystalProjectTracker.Models;
using CrystalProjectTracker.Repository.FeatureRepository;
using CrystalProjectTracker.Repository.ModuleRepository;
using CrystalProjectTracker.Repository.ProjectRepository;
using CrystalProjectTracker.Services.DTO;
using CrystalProjectTracker.Services.FeatureService;
using CrystalProjectTracker.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static ClientNotifications.Helpers.NotificationHelper;

namespace CrystalProjectTracker.Controllers
{
    public class FeatureController : Controller
    {
        private IFeatureRepository _featureRepository;
        private IFeatureService _featureService;
        private IModuleRepository _moduleRepository;
        private IProjectRepository _projectRepository;
        private IClientNotification _clientNotification;

        public FeatureController(IFeatureRepository featureRepository,IFeatureService featureService, IModuleRepository moduleRepository,IProjectRepository projectRepository, IClientNotification clientNotification)
        {
            _featureRepository = featureRepository;
            _featureService = featureService;
            _moduleRepository = moduleRepository;
            _projectRepository = projectRepository;
            _clientNotification = clientNotification;
        }
        // GET: Feature
        public ActionResult Index(int project_id = 0,int module_id = 0)
        {
            IList<Feature> feature_list;
            var project = new List<Project>();
            var module = new List<Module>();

            project.AddRange(_projectRepository.getAll());

            if (project_id > 0)
            {
                module.AddRange(_moduleRepository.GetModuleByProjectId(project_id));
                feature_list = _featureRepository.GetFeatureByModuleId(module_id);
            }
            else
            {
                module.AddRange(_moduleRepository.getAll());
                feature_list = _featureRepository.getAll();
            }
                

            ViewBag.projects = new SelectList(project, "project_id", "project_name");

            
            ViewBag.modules = new SelectList(module, "module_id", "module_name");

            var model = new FeatureListViewModel()
            {
                features = feature_list.ToList(),
                features_count = feature_list.Count
            };
            return View(model);
        }


        // GET: Feature/Create
        public ActionResult Create(int project_id = 0)
        {
            var project = new List<Project>();
            var module = new List<Module>();

            project.AddRange(_projectRepository.getAll());

            ViewBag.projects = new SelectList(project, "project_id", "project_name");

            return View();
        }

        // POST: Feature/Create
        [HttpPost]
        public ActionResult Create(FeatureDTO feature_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _featureService.Create(feature_dto);
                    _clientNotification.AddToastNotification("Feature Successfully Created.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Feature/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var project = new List<Project>();
                var module = new List<Module>();

                project.AddRange(_projectRepository.getAll());
                ViewBag.projects = new SelectList(project, "project_id", "project_name");

                var feature = _featureRepository.getById(id);
                if (feature == null)
                {
                    throw new Exception("Cannot retrive data of that feature.");
                }
                return View(feature);
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public ActionResult Edit(FeatureDTO feature_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _featureService.Update(feature_dto);
                    _clientNotification.AddToastNotification("Feature Successfully Updated.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Delete(int feature_id)
        {
            try
            {
                _featureService.Delete(feature_id);
                _clientNotification.AddToastNotification("Feature Successfully Deleted.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult getModulesFromProject([FromBody]ModuleDTO module_dto)
        {
            try
            {
                List<ModuleDTO> modulelist = new List<ModuleDTO>();
                List<Module> modules = _moduleRepository.GetModuleByProjectId(module_dto.project_id).ToList();
                foreach (var module in modules)
                {
                    modulelist.Add(new ModuleDTO() { module_id = module.module_id, module_name = module.module_name });
                }
                return Json(modulelist);
            }
            catch (Exception)
            {
                string responseMessage = "There was Problem while performing the operation";
                return NotFound(Json(new { success = false, responseText = responseMessage }));
            }
        }
    }
}

CrystalProjectTracker/Controllers/ModuleController.cs
using ClientNotifications;
using CrystalProjectTracker.Models;
using CrystalProjectTracker.Repository.ModuleRepository;
using CrystalProjectTracker.Repository.ProjectRepository;
using CrystalProjectTracker.Services.DTO;
using CrystalProjectTracker.Services.ModuleService;
using CrystalProjectTracker.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using static ClientNotifications.Helpers.NotificationHelper;

namespace CrystalProjectTracker.Controllers
{
    public class ModuleController : Controller
    {
        private IClientNotification _clientNotification;
        private IModuleRepository _moduleRepository;
        private IProjectRepository _projectRepository;
        private IModuleService _moduleService;

        public ModuleController(IModuleRepository moduleRepository, IProjectRepository projectRepository,IModuleService moduleService,IClientNotification clientNotification)
        {
            _clientNotification = clientNotification;
            _moduleRepository = moduleRepository;
            _projectRepository = projectRepository;
            _moduleService = moduleService;
        }
        // GET: Module
        public ActionResult Index(int project_id = 0)
        {
            IList<Module> module_list;

            if (_moduleRepository.GetModuleByProjectId(project_id) != null && project_id > 0)
            {
                module_list = _moduleRepository.GetModuleByProjectId(project_id);
            }
            else
            {
                module_list = _moduleRepository.getAll();
            }
            var project = new List<Project>();
            project.AddRange(_projectRepository.getAll());
            ViewBag.projects = new SelectList(project, "project_id", "project_name");

            var model = new ModuleListViewModel()
            {
                modules = module_list.ToList(),
                modules_count = module_list.Count
            };
            return View(model);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            var project = new List<Project>();
            project.AddRange(_projectRepository.getAll());
            ViewBag.projects = new SelectList(project, "project_id", "project_name");

            return View();
        }

        // POST: Module/Create
        [HttpPost]
        public ActionResult Create(ModuleDTO module_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _moduleService.Create(module_dto);
                    _clientNotification.AddToastNotification("Module Successfully Created.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Module/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var project = new List<Project>();
                project.AddRange(_projectRepository.getAll());
                ViewBag.projects = new SelectList(project, "project_id", "project_name");

                var module = _moduleRepository.getById(id);
                if(module == null)
                {
                    throw new Exception("Cannot retrive data of that module.");
                }
                return View(module);
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Module/Edit/5
        [HttpPost]
        public ActionResult Edit(ModuleDTO module_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _moduleService.Update(module_dto);
                    _clientNotification.AddToastNotification("Module Successfully Updated.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Module/Delete/5
        [HttpPost]
        public ActionResult Delete(int module_id)
        {
            try
            {
                _moduleService.Delete(module_id);
                _clientNotification.AddToastNotification("Module Successfully Deleted.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CrystalProjectTracker/Controllers/UserController.cs
using System;
using ClientNotifications;
using CrystalProjectTracker.Repository.ModuleRepository;
using CrystalProjectTracker.Repository.ProjectRepository;
using CrystalProjectTracker.Repository.UserRepository;
using CrystalProjectTracker.Services.DTO;
using CrystalProjectTracker.Services.UserService;
using CrystalProjectTracker.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static ClientNotifications.Helpers.NotificationHelper;


namespace CrystalProjectTracker.Controllers
{
    public class UserController : Controller
    {
        private readonly IClientNotification _clientNotification;
        private readonly IUserRepository _userRepository;
        private readonly IUserService _userService;

        public UserController(IUserRepository userRepository, IClientNotification clientNotification,IUserService userService)
        {
            _clientNotification = clientNotification;
            _userRepository = userRepository;
            _userService = userService;
        }

        // GET: User
        public ActionResult Index()
        {
            var user_list = _userRepository.getAll();
            var model = new UserListViewModel()
            {
                users = user_list,
                users_count = user_list.Count
            };
            return View(model);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(UserDTO user_dto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userService.Create(user_dto);
                    _clientNotification.AddToastNotification("User Successfully Created.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                }
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var user = _userRepository.getById(id);
                return View(user);
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: User/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                _userService.Delete(id);
                _clientNotification.AddToastNotification("User Successfully Deleted.", NotificationType.success, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            catch (Exception e)
            {
                _clientNotification.AddToastNotification(e.Message.ToString(), NotificationType.error, new ToastNotificationOption { PositionClass = "toast-top-right", CloseButton = true });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CrystalProjectTracker/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Version 1.0
    </div>
    <div>
        <strong>Copyright</strong> Crystal Project Tracker &copy; @DateTime.Now.Year
    </div>
</div>

CrystalProjectTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Crystal Project Tracker</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {
        @RenderSection("Styles", required: false)
    }

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/Font-Awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/lib/toastr/toastr.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-sweetalert/dist/sweetalert.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/Font-Awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/lib/toastr/toastr.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-sweetalert/dist/sweetalert.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>

</head>
<body>
    @await Component.InvokeAsync("ClientNotifications.Notify")

    <partial name="_CookieConsentPartial" />
    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <partial name="_Navigation" />

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg dashbard-1">

            <!-- Top Navbar -->
            <partial name="_TopNavbar" />

            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>
                        @ViewData["Title"]
                    </h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li class="active">
                            <strong>
                                @ViewData["Title"]
                            </strong>
                        </li>
                    </ol>
                </div>
            </div>
            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            <partial name="_Footer" />

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <script src="~/lib/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

        <script src="~/lib/toastr/toastr.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-sweetalert/dist/sweetalert.min.js" asp-append-version="true"></script>

        <script src="~/js/script.js"></script>
        <script src="~/lib/PACE/pace.min.js"></script>


    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <script src="~/lib/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

        <script src="~/lib/toastr/toastr.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-sweetalert/dist/sweetalert.min.js" asp-append-version="true"></script>

        <script src="~/js/script.js"></script>
        <script src="~/lib/PACE/pace.min.js"></script>

    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

CrystalProjectTracker/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="~/Images/profile_small.jpg" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Sandip Chaudhary</strong>
                            </span> <span class="text-muted text-xs block">Admin <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInDown m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    <img alt="image" class="img-circle img-sm" src="~/Images/profile_small.jpg" />
                </div>
            </li>
            <li class="@(Html.IsMenuActive("/Home") ? "active" : "")">
                <a asp-action="Index" asp-controller="Home"><i class="fa fa-dashboard"></i> <span class="nav-label">Dashboard</span> </a>
            </li>
            <li class="@(Html.IsMenuActive("/User") ? "active" : "")">
                <a href="#"><i class="fa fa-users"></i> <span class="nav-label">User</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="@(Html.IsMenuActive("/User/Index") ? "active" : "")"><a asp-action="Index" asp-controller="User"> All Users </a></li>
                    <li class="@(Html.IsMenuActive("/User/Create") ? "active" : "")"><a asp-action="Create" asp-controller="User"> Create Users </a></li>
                </ul>
            </li>
            <li class="@(Html.IsMenuActive("/Project") ? "active" : "")">
                <a href="#"><i class="fa fa-flask"></i> <span class="nav-label">Project</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="@(Html.IsMenuActive("/Project/Index") ? "active" : "")"><a asp-action="Index" asp-controller="Project"> All Projects </a></li>
                    <li class="@(Html.IsMenuActive("/Project/Create") ? "active" : "")"><a asp-action="Create" asp-controller="Project"> Add Project </a></li>
                </ul>
            </li>
            <li class="@(Html.IsMenuActive("/Module") ? "active" : "")">
                <a href="#"><i class="fa fa-cubes"></i> <span class="nav-label">Module</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="@(Html.IsMenuActive("/Module/Index") ? "active" : "")"><a asp-action="Index" asp-controller="Module"> All Module </a></li>
                    <li class="@(Html.IsMenuActive("/Module/Create") ? "active" : "")"><a asp-action="Create" asp-controller="Module"> Add Module </a></li>
                </ul>
            </li>
            <li class="@(Html.IsMenuActive("/Feature") ? "active" : "")">
                <a href="#"><i class="fa fa-star"></i> <span class="nav-label">Features</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="@(Html.IsMenuActive("/Feature/Index") ? "active" : "")"><a asp-action="Index" asp-controller="Feature"> All Feature </a></li>
                    <li class="@(Html.IsMenuActive("/Feature/Create") ? "active" : "")"><a asp-action="Create" asp-controller="Feature"> Add Feature </a></li>
                </ul>
            </li>
            <li class="@(Html.IsMenuActive("/Issue") ? "active" : "")">
                <a href="#"><i class="fa fa-exclamation-circle"></i> <span class="nav-label">Issue Tracker</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="@(Html.IsMenuActive("/Issue/Index") ? "active" : "")"><a asp-action="Index" asp-controller="Issue"> All Issues </a></li>
                    <li class="@(Html.IsMenuActive("/Issue/Create") ? "active" : "")"><a asp-action="Create" asp-controller="Issue"> Create Issue </a></li>
                </ul>
            </li>
            <li class="@(Html.IsMenuActive("/FileManager") ? "active" : "")">
                <a href="/fileManager"><i class="fa fa-folder"></i> <span class="nav-label">File Manager</span></a>
            </li>
            <li class="@(Html.IsMenuActive("/Statistics") ? "active" : "")">
                <a href="/statistics"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Statistics</span></a>
            </li>
            <li class="@(Html.IsMenuActive("/Setting") ? "active" : "")">
                <a href="#"><i class="fa fa-cog"></i> <span class="nav-label">Settings</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="/Setting/YearSetup">Year Setup</a></li>
                    <li><a href="/Setting/MonthSetup">Month Setup</a></li>
                    <li><a href="/Setting/WorkingDays">WorkingDays Setup</a></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>